# For use in mybinder.org
FROM andrewosh/binder-base

MAINTAINER Agile Scientific <hello@agilescientific.com>

USER root

USER main

# Copy from the Dockerfile generated by binder to create and activate the environment.
ADD environment.yml environment.yml
RUN conda env create -n binder
RUN echo "export PATH=/home/main/anaconda2/envs/binder/bin/:/home/main/anaconda3/envs/binder/bin/:$PATH" >> ~/.binder_start
RUN conda install -n binder jupyter
RUN /bin/bash -c "source activate binder && jupyter kernelspec install-self --user"

# To get around the new default authentication in Jupyter
RUN mkdir $HOME/.jupyter
RUN echo "c.NotebookApp.token = ''" >> $HOME/.jupyter/jupyter_notebook_config.py
RUN echo "c.NotebookApp.password=''" >> $HOME/.jupyter/jupyter_notebook_config.py
RUN echo "c.NotebookApp.password_required=False" >> $HOME/.jupyter/jupyter_notebook_config.py

