#This is my second submission

```{r}
#Remove the comment below and install if you don't have the package already installed.
#install.packages('randomForest')
library(randomForest)
```

#Reading the file
```{r}
train_prod = read.csv('facies_vectors.csv')
test_prod = read.csv('nofacies_data.csv')
```


#Check the structure of the file 
```{r}
str(train_prod)
str(test_prod)
```


#Removing the rows with NA's
```{r}
train_prod = train_prod[!is.na(train_prod$PE),]
```


#Converting the Facies column to factor
```{r}
train_prod$Facies = as.factor(as.character(train_prod$Facies))
```

#Splitting into train and local validation test
```{r}
train_row = sample(nrow(train_prod), 0.7*nrow(train_prod), replace=F)
train_local = train_prod[train_row,]
test_local  = train_prod[-train_row,]
```

#Creating SVM model
```{r}
RF.local.model = randomForest(Facies~., data = train_local[!colnames(train_local) %in% c('Formation',
                                                                                 'Well.Name',
                                                                                 'Depth'
                                                                                 )])
RF.local.pred = predict(RF.local.model, newdata = test_local)
```

#Local validation set accuracy
```{r}
acc_table_RF = table(RF.local.pred, test_local$Facies)
acc_table_RF
acc_RF = sum(diag(acc_table_RF))/nrow(test_local)
acc_RF
```


#Predicting on the blind dataset
```{r}
RF.prod.pred = predict(RF.local.model, newdata = test_prod)
```

#Forming the submission file
```{r}
sub = cbind(test_prod, Facies = RF.prod.pred)
```

#Writting the predicted output file
```{r}
write.csv(sub, row.names= F, 'RF_predicted_facies_1.csv')
```

